name: Linting & Coverage
on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: ðŸ§ª Linting & Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: ${{ vars.RTLDEV_MW_CI_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Python version
        run: |
          echo "Python version: "
          echo ${{ vars.RTLDEV_MW_CI_PYTHON_VERSION }} | sed 's/./&â€Ž/g'
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v4
        env:
          FILTER_REGEX_INCLUDE: "/hexonet/*|/scripts/*|updateVersion*.sh|setup.py"
          DEFAULT_BRANCH: master
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage Report
        run: "./scripts/coverage.sh"
