name: validate
on:
  push:
    branches:
      - "gh-pages*"
  pull_request:
    branches:
      - "gh-pages*"

jobs:
  validate:
    name: validate css, html, and js
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Set up our Nodejs
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      # Runs validation test
      - name: validation test
        run: |
          npm prune && npm i
          gulp validate
